name: Generate Action

on:
  workflow_dispatch:
    inputs:
      liquibase-version:
        description: 'Liquibase version'
        required: true
        default: '4.26.0'

jobs:
  create-command-list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build liquibase-protobuf-generator
        run: docker build -t liquibase-protobuf-generator:${{ inputs.liquibase-version }} . --build-arg VERSION=${{ inputs.liquibase-version }}

      - name: Generate liquibase command list
        run: docker run --rm -v $(pwd):/proto liquibase-protobuf-generator:${{ inputs.liquibase-version }} --output-file=commands.json list-commands

      - name: Iterate over commands and execute Docker command
        run: |
          COMMANDS=$(cat commands.json | jq -r '.[]')
          IFS=$'\n'
          for command in $COMMANDS; do
            docker run --rm -v $(pwd):/proto liquibase-protobuf-generator:${{ inputs.liquibase-version }} generate-protobuf --target-command="$command" --output-dir /proto
          done
          mkdir -p proto-commands
          mv *.proto ./proto-commands

      - name: Configure git user
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "liquibot"
          git config --global user.email "liquibot@liquibase.org"

      - name: Push changes
        run: |
          git add /proto/commands
          git commit -m "Generated protobuf files for liquibase version ${{ inputs.liquibase-version }}"
          git push
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: commands-${{ inputs.liquibase-version }}
          path: /proto/commands
