name: Generate Action

on:
  workflow_dispatch:
    inputs:
      liquibase-version:
        description: 'Liquibase version'
        required: true
        default: '4.26.0'

jobs:
  create-command-list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build liquibase-protobuf-generator
        run: docker build -t liquibase-protobuf-generator:{{ inputs.liquibase-version }} . --build-arg VERSION={{ inputs.liquibase-version }}

      - name: Generate liquibase commands
        run: docker run --rm -v $(PWD):/proto liquibase-protobuf-generator:$(VERSION) --output-file=commands.json list-commands

      - uses: actions/upload-artifact@v3
        with:
          name: commands-$LIQUIBASE_VERSION
          path: commands.json
